[package]
name = "iota-js"
version = "0.1.0"
authors = ["Andreas C. Osowski <andreas@osowski.de>"]

[dependencies]
iota-sign = { git = "https://github.com/th0br0/iota.rs", branch = "to-space-and-back" }
iota-trytes = { git = "https://github.com/th0br0/iota.rs", branch = "to-space-and-back" }
iota-curl = { git = "https://github.com/th0br0/iota.rs", branch = "to-space-and-back" }
